(function(){var Tag;
Tag=function(){function b(a,c,d){this.type=a;if(c==null)c={};this.doc=d!=null?d:document;this.attributes=HashUtil.merge_copy(b.defaults(this.type),c)}b.defaults=function(a){switch(a){case "script":return{type:"text/javascript"};case "img":return{width:"1",height:"1",border:"0",alt:"",style:{display:"none"}};case "iframe":return{width:0,height:0,marginWidth:0,marginHeight:0,frameBorder:0,scrolling:"no"};default:return{}}};b.prototype.to_html_string=function(){var a,c,d,f,e;d="<"+this.type;e=this.attributes;
for(a in e){f=e[a];c=a.toLowerCase();if(!this._is_object(f)&&a!=="innerHTML"&&a!=="text")d+=" "+c+"='"+f+"'";if(a==="style")d+=" "+c+"='"+this._get_style_string(f)+"'"}d+=">";if(this.attributes.text!=null)d+=""+this.attributes.text;if(this.attributes.innerHTML!=null)d+=""+this.attributes.innerHTML;d+="</"+this.type+">";return d};b.prototype.to_element=function(){var a,c,d,f;c=this.doc.createElement(this.type);f=this.attributes;for(a in f){d=f[a];this.set_property(c,a,d)}return c};b.prototype.set_invisible=
function(){var a;if((a=this.attributes).style==null)a.style={};return this.attributes.style.display="none"};b.prototype.set_property=function(a,c,d){return(!this._is_object(d)?this._set_single_property:this._set_multiple_properties)(a,c,d)};b.prototype._get_style_string=function(a){var c,d,f;d="";for(c in a){f=a[c];d+=""+c+": "+f+"; "}return d};b.prototype._is_object=function(a){return typeof a==="object"};b.prototype._set_single_property=function(a,c,d){return a[c]=d};b.prototype._set_multiple_properties=
function(a,c,d){var f,e,g;g=[];for(f in d){e=d[f];g.push(a[c][f]=e)}return g};return b}();var HashUtil;HashUtil=function(){function b(){}b.clone=function(a){return this.merge(a,{})};b.merge=function(a,c){var d;for(d in a)if(a.hasOwnProperty(d)&&c[d]==null)c[d]=a[d];return c};b.merge_copy=function(a,c){return this.merge(a,this.clone(c))};return b}();var DOMUtil;
DOMUtil=function(){function b(a,c){this.context=a;this.attachment_strategy=c!=null?c:b.append;this.doc=this.context.doc;this.body=this.context.doc.body}b.append=function(a,c){return c.appendChild(a.to_element())};b.write=function(a,c,d){return d.write(a.to_html_string())};b.prototype.create_tag=function(a,c){return new Tag(a,c)};b.prototype.write_script=function(a,c){if(a==null)a={};if(c==null)c=this.body;this.attachment_strategy(new Tag("script",a),c,this.doc)};b.prototype.write_iframe=function(a,
c){if(a==null)a={};if(c==null)c=this.body;this.attachment_strategy(new Tag("iframe",a),c,this.doc)};b.prototype.write_and_throw_error=function(a){this.write_script(a);throw a;};b.prototype.write_pixel=function(a,c){if(a==null)a={};if(c==null)c=this.body;this.attachment_strategy(new Tag("img",a),c,this.doc)};return b}();var Context;Context=function(){return function(b,a,c){this.doc=b;this.win=a;this.clock=c}}();var dom_ready;
dom_ready=function(){var b;b=false;return function(a){var c,d,f;d=function(){if(!b){b=true;return a()}};c=function(){try{document.documentElement.doScroll("left")}catch(e){setTimeout(c,1);return}return d()};if(document.readyState==="complete")return d();if(document.addEventListener){document.addEventListener("DOMContentLoaded",d,false);return window.addEventListener("load",d,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",d);window.attachEvent("onload",d);if((typeof document!==
"undefined"&&document!==null?(f=document.documentElement)!=null?f.doScroll:void 0:void 0)&&(typeof window!=="undefined"&&window!==null?window.frameElement:void 0)===null)return c()}}}();var SectionZoneUtil;
SectionZoneUtil=function(){var b,a,c,d,f;b={"671408":"bus","466135":"remnant","482908":"_franb","481858":"_fran","653457":"us","653461":"can","731052":"uk","680903":"free","680904":"paid","658386":"mkt_top","658387":"mkt_bot","658391":"sea_top","658064":"ROS_LT","658063":"ROS_RT","622280":"dash","449137":"test","475159":"goog","583310":"addbk","583311":"conn","583312":"cont","583313":"ecard","583315":"ecard_rec","583317":"ecard_sen","583319":"ecard_vie","583320":"fanp","583321":"grps","583324":"home",
"583326":"jobs","583329":"mess","583330":"misc","583333":"photo","583334":"prof","583335":"sear","583336":"sett","635260":"career","637299":"head","637300":"rt_top","637301":"rt_bot","637302":"lt_top","637303":"lt_bot","583686":"ppci","587863":"ppcd","591192":"pppi","591193":"pppd","617015":"apple","661722":"inter","553068":"logg","559078":"exp","570230":"nydnews","623936":"nbcspo","579120":"free","420403":"newsbus"};d=function(e){return e.search(/[^0-9]/)!==-1};a=function(e,g){if(g==null)g=".";return e[e.length-
1].length===2&&e[e.length-2]==="co"?e.slice(e.length-3,e.length).join(g):e.slice(e.length-2,e.length).join(g)};c=function(e){var g;g=[];if((e.override_domain()!=null?true:!e.is_file_protocol())&&e.use_domain()){e=e.hostname().toLowerCase().split(".");if(e.length>1)g=e}return g};f={};f.get_zone=function(e,g){var h,i;if(g==null)g=null;h=(i=b[e])!=null?i:"_default";if(h==="_default")h=d(e)?e:g;return h};f.get_appnexus_sitename=function(e){e=c(e);return e.length>1?a(e,"_"):e.join("_")};return f}();var AppNexusAdCodeBuilder;
AppNexusAdCodeBuilder=function(){var b,a;b=function(c){var d,f;d=[c.pid()];f=SectionZoneUtil.get_appnexus_sitename(c);f!==""&&d.push(f);f=SectionZoneUtil.get_zone(c.section_id(),"_default");f=f.replace(/[^a-zA-Z0-9_]+/g,"_");d.push(f);d.push(c.ad_size());return d.join("__")};a={};a.build=function(c){var d,f,e;f=c.use_iframe()?"tt":"ttj";d=(c.protocol()==="https:"?"https://secure":"http://ib")+".adnxs.com";d=(e=c.test_base_url())!=null?e:d;return""+d+"/"+f+"?member=232&inv_code="+b(c)+"&size="+c.ad_size()};
return a}();var AdTagSettings;
AdTagSettings=function(){function b(a){this.context=a}b.prototype.pid=function(){return this.context.win._bizo_ad_partner_id+""};b.prototype.section_id=function(){return this.context.win._bizo_ad_section_id+""};b.prototype.ad_width=function(){return this.context.win._bizo_ad_width};b.prototype.ad_height=function(){return this.context.win._bizo_ad_height};b.prototype.ad_size=function(){return""+this.ad_width()+"x"+this.ad_height()};b.prototype.target_element_id=function(){return this.context.win._bizo_ad_target_element_id};b.prototype.force_iframe=
function(){return this.context.win._bizo_ad_force_iframe};b.prototype.use_iframe=function(){var a;return(a=this.force_iframe())!=null?a:this.target_element_id()!=null};b.prototype.ignore_domain=function(){return this.context.win._bizo_ad_ignore_domain};b.prototype.use_domain=function(){return this.ignore_domain()!==true};b.prototype.protocol=function(){return this.location().protocol};b.prototype.location=function(){return this.context.win.location};b.prototype.is_file_protocol=function(){return this.protocol()===
"file:"};b.prototype.hostname=function(){var a,c;a=this.context.win.location.hostname;if(this.override_domain()!=null)a=this.override_domain();else if(this.is_file_protocol())a="";else if(this.context.win.parent!==this.context.win&&this.referrer()!=null){c=/^(https{0,1}:\/\/){0,1}(([-a-z0-9]+\.){1,}([a-z]{2,4}))(.*)$/;c=c.exec(this.context.doc.referrer.toLowerCase());if(c!==null&&c.length>=3)a=c[2]}return a};b.prototype.override_domain=function(){return this.context.win._bizo_ad_override_domain};
b.prototype.test_base_url=function(){return this.context.win._bizo_ad_test_base_url};b.prototype.referrer=function(){return this.context.doc.referrer};return b}();var BaseLogger,ConsoleLogger,ErrorLog,LocalLogger,PixelLogger,__slice=Array.prototype.slice,__hasProp=Object.prototype.hasOwnProperty,__extends=function(b,a){function c(){this.constructor=b}for(var d in a)if(__hasProp.call(a,d))b[d]=a[d];c.prototype=a.prototype;b.prototype=new c;b.__super__=a.prototype;return b};
ErrorLog=function(){function b(){}b.log=function(){var a,c,d,f,e,g,h;a=arguments[0];c=arguments[1];f=3<=arguments.length?__slice.call(arguments,2):[];h=[];e=0;for(g=f.length;e<g;e++){d=f[e];h.push(d.log(a,c))}return h};return b}();BaseLogger=function(){function b(){}b.map_error_data=function(a,c,d){var f,e;if(d==null)d=function(g){return g};return function(){var g;g=[];for(f in a){e=a[f];g.push(""+f+"="+d(e))}return g}().join(c)};return b}();
PixelLogger=function(){function b(){b.__super__.constructor.apply(this,arguments)}__extends(b,BaseLogger);b.http_host="http://error.bizographics.com";b.https_host="https://dbsugv5o22gme.cloudfront.net";b.set_pixel_path=function(a){return this.pixel_path=a};b.log=function(a,c){var d,f,e;d=a.win.location.protocol==="https:"?this.https_host:this.http_host;f=this.map_error_data(c,"&",encodeURIComponent);e=new Image(1,1);e.src=""+d+"/"+this.pixel_path+"?"+f;return e};return b}();
ConsoleLogger=function(){function b(){b.__super__.constructor.apply(this,arguments)}__extends(b,BaseLogger);b.log=function(a,c){var d;d=this.map_error_data(c,", ");if(typeof console!=="undefined"&&console!==null&&console.log!=null)return console.log(d)};return b}();LocalLogger=function(){function b(){b.__super__.constructor.apply(this,arguments)}__extends(b,BaseLogger);b.errors=[];b.log=function(a,c){return this.errors.push(c)};return b}();var AdTagErrorLog;
AdTagErrorLog=function(){function b(){}b.log=function(a,c){var d;d={tag_type:"ad_tags",pid:a.win._bizo_ad_partner_id,section_id:a.win._bizo_ad_section_id,ad_width:a.win._bizo_ad_width,ad_height:a.win._bizo_ad_height,ref:a.doc.referrer,error:c};PixelLogger.set_pixel_path("ad_tags/error.gif");ErrorLog.log(a,d,PixelLogger);if(a.win._bizo_debug===true){a.win.LocalLogger=LocalLogger;return ErrorLog.log(a,d,ConsoleLogger,LocalLogger)}};return b}();
var AdTags,context,__bind=function(b,a){return function(){return b.apply(a,arguments)}};
AdTags=function(){function b(a){this.context=a;this.append_tag=__bind(this.append_tag,this);this.settings=new AdTagSettings(this.context)}b.prototype.check_required_params=function(){if(!(this.settings.pid()&&this.settings.section_id()&&this.settings.ad_width()&&this.settings.ad_height()))throw"You are missing one of the following parameters: _bizo_ad_partner_id, _bizo_ad_section_id, _bizo_ad_width and/or _bizo_ad_height";};b.prototype.build_tag_url=function(){this.check_required_params();return AppNexusAdCodeBuilder.build(this.settings)};
b.prototype.append_tag=function(){var a,c;try{c=this.settings.target_element_id()!=null?this.context.doc.getElementById(this.settings.target_element_id()):this.context.doc.body;a={src:this.build_tag_url(),width:this.settings.ad_width(),height:this.settings.ad_height()};return(new DOMUtil(this.context)).write_iframe(a,c)}catch(d){return AdTagErrorLog.log(new Context(document,window),d)}};b.prototype.execute=function(){var a;if(this.settings.use_iframe())if(this.settings.target_element_id()!=null)return dom_ready(this.append_tag);
else{a={src:this.build_tag_url(),width:this.settings.ad_width(),height:this.settings.ad_height(),id:"bizo-ad-write"};return(new DOMUtil(this.context,DOMUtil.write)).write_iframe(a)}else return(new DOMUtil(this.context,DOMUtil.write)).write_script({src:this.build_tag_url()})};return b}();
try{context=new Context(document,window);(new AdTags(context)).execute()}catch(e$$1){try{AdTagErrorLog.log(new Context(document,window),e$$1)}catch(e2){document.write('<script type="text/javascript">//Bizo Ad Tag Exception: [error 1]['+e$$1+"],[error 2]["+e2+"]<\/script>")}};})();
