(function(){var g=this,h=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var d=Object.prototype.toString.call(a);if("[object Window]"==d)return"object";if("[object Array]"==d||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==d||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};var k=parseFloat("0.06"),l=isNaN(k)||1<k||0>k?0:k;var n=function(a){return-1!=m.indexOf(a)};var p=function(a,b){for(var d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.call(null,a[d],d,a)};var m=g.navigator?g.navigator.userAgent:"";var q=n("Opera")||n("OPR"),r=n("Trident")||n("MSIE"),s=n("Gecko")&&!n("WebKit")&&!(n("Trident")||n("MSIE")),t=n("WebKit");(function(){var a="",b;if(q&&g.opera)return a=g.opera.version,"function"==h(a)?a():a;s?b=/rv\:([^\);]+)(\)|;)/:r?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:t&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(m))?a[1]:"");return r&&(b=(b=g.document)?b.documentMode:void 0,b>parseFloat(a))?String(b):a})();var u=function(a){this.b=[];this.a={};for(var b=0,d=arguments.length;b<d;++b)this.a[arguments[b]]=""},x=function(){var a=v,b="317150500 317150501 317150502 317150503 317150504 317150505".split(" ");if(a.a.hasOwnProperty(1)&&""==a.a[1]){e:{if(!(1E-4>Math.random())){var d=Math.random();if(d<l){try{var c=new Uint16Array(1);window.crypto.getRandomValues(c);d=c[0]/65536}catch(e){d=Math.random()}b=b[Math.floor(d*b.length)];break e}}b=null}b&&""!=b&&a.a.hasOwnProperty(1)&&(a.a[1]=b)}};
u.prototype.c=function(a){return this.a.hasOwnProperty(a)?this.a[a]:""};u.prototype.geil=u.prototype.c;var y=function(){var a=v,b=[];p(a.a,function(a){""!=a&&b.push(a)});return 0<a.b.length&&0<b.length?a.b.join(",")+","+b.join(","):a.b.join(",")+b.join(",")};var v,z="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency_code google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_remarketing_only google_remarketing_for_search google_conversion_items google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_is_call google_conversion_page_url".split(" ");
function A(a){return null!=a?escape(a.toString()):""}function B(a){return null!=a?a.toString().substring(0,512):""}function C(a,b){var d=A(b);if(""!=d){var c=A(a);if(""!=c)return"&".concat(c,"=",d)}return""}function D(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")}
function E(a){var b;if((a=a.google_custom_params)&&"object"==typeof a&&"function"!=typeof a.join){var d=[];for(b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];if(c&&"function"==typeof c.join){for(var e=[],f=0;f<c.length;++f){var w=D(c[f]);null!=w&&e.push(w)}c=0==e.length?null:e.join(",")}else c=D(c);(e=D(b))&&null!=c&&d.push(e+"="+c)}b=d.join(";")}else b="";return""==b?"":"&".concat("data=",encodeURIComponent(b))}
function F(a){return"number"!=typeof a&&"string"!=typeof a?"":A(a.toString())}function G(a){if(!a)return"";a=a.google_conversion_items;if(!a)return"";for(var b=[],d=0,c=a.length;d<c;d++){var e=a[d],f=[];e&&(f.push(F(e.value)),f.push(F(e.quantity)),f.push(F(e.item_id)),f.push(F(e.adwords_grouping)),f.push(F(e.sku)),b.push("("+f.join("*")+")"))}return 0<b.length?"&item="+b.join(""):""}
function H(a,b,d){var c=[];if(a){var e=a.screen;e&&(c.push(C("u_h",e.height)),c.push(C("u_w",e.width)),c.push(C("u_ah",e.availHeight)),c.push(C("u_aw",e.availWidth)),c.push(C("u_cd",e.colorDepth)));a.history&&c.push(C("u_his",a.history.length))}d&&"function"==typeof d.getTimezoneOffset&&c.push(C("u_tz",-d.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&&c.push(C("u_java",b.javaEnabled())),b.plugins&&c.push(C("u_nplug",b.plugins.length)),b.mimeTypes&&c.push(C("u_nmime",b.mimeTypes.length)));
return c.join("")}function I(a,b,d){var c="";if(b){var e;if(a.top==a)e=0;else{var f=a.location.ancestorOrigins;if(f)e=f[f.length-1]==a.location.origin?1:2;else{f=a.top;try{e=!!f.location.href||""===f.location.href}catch(w){e=!1}e=e?1:2}}f="";f=d?d:1==e?a.top.location.href:a.location.href;c+=C("frm",e);c+=C("url",B(f));c+=C("ref",B(b.referrer))}return c}function J(a){return a&&a.location&&a.location.protocol&&"https:"==a.location.protocol.toString().toLowerCase()?"https:":"http:"}
function K(a){return a.google_remarketing_only?"googleads.g.doubleclick.net":a.google_conversion_domain||"www.googleadservices.com"}
function L(a,b,d,c){var e="/?";"landing"==c.google_conversion_type&&(e="/extclk?");var e=J(a)+"//"+K(c)+"/pagead/"+[c.google_remarketing_only?"viewthroughconversion/":"conversion/",A(c.google_conversion_id),e,"random=",A(c.google_conversion_time)].join(""),f;e:{f=c.google_conversion_language;if(null!=f){f=f.toString();if(2==f.length){f=C("hl",f);break e}if(5==f.length){f=C("hl",f.substring(0,2))+C("gl",f.substring(3,5));break e}}f=""}a=[C("cv",c.google_conversion_js_version),C("fst",c.google_conversion_first_time),
C("num",c.google_conversion_snippets),C("fmt",c.google_conversion_format),C("value",c.google_conversion_value),C("currency_code",c.google_conversion_currency_code),C("label",c.google_conversion_label),C("oid",c.google_conversion_order_id),C("bg",c.google_conversion_color),f,C("guid","ON"),C("disvt",c.google_disable_viewthrough),C("is_call",c.google_is_call),C("eid",y()),G(c),H(a,b,c.google_conversion_date),E(c),I(a,d,c.google_conversion_page_url),c.google_remarketing_for_search&&!c.google_conversion_domain?
"&srr=n":""].join("");return e+a}function M(){var a=N,b=document,d=O,c;c=J(a)+"//www.google.com/ads/user-lists/"+[A(d.google_conversion_id),"/?random=",Math.floor(1E9*Math.random())].join("");return c+=[C("label",d.google_conversion_label),C("fmt","3"),I(a,b,d.google_conversion_page_url)].join("")}
function P(a){return{ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a]?a+".html":"en_US.html"}
function Q(){var a=N,b=navigator,d=document,c=N;3!=c.google_conversion_format||c.google_remarketing_only||c.google_conversion_domain||v&&x();var e=v?v.c(1):"",b=L(a,b,d,c),d=function(a,b,c){return'<img height="'+c+'" width="'+b+'" border="0" alt="" src="'+a+'" />'};return 0==c.google_conversion_format&&null==c.google_conversion_domain?'<a href="'+(J(a)+"//services.google.com/sitestats/"+P(c.google_conversion_language)+"?cid="+A(c.google_conversion_id))+'" target="_blank">'+d(b,135,27)+"</a>":1<c.google_conversion_snippets||
3==c.google_conversion_format?"317150501"==e||"317150502"==e||"317150503"==e||"317150504"==e||"317150505"==e?d(b,1,1)+('<script src="'+b.replace(/(&|\?)fmt=3(&|$)/,"$1fmt=4&adtest=on$2")+'">\x3c/script>'):d(b,1,1):'<iframe name="google_conversion_frame" title="Google conversion frame" width="'+(2==c.google_conversion_format?200:300)+'" height="'+(2==c.google_conversion_format?26:13)+'" src="'+b+'" frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no">'+
d(b.replace(/\?random=/,"?frame=0&random="),1,1)+"</iframe>"}function R(){return new Image}function S(){var a=O,b=M(),d=R;"function"===typeof a.opt_image_generator&&(d=a.opt_image_generator);a=d();b+=C("async","1");a.src=b;a.onload=function(){}};var N=window;
if(N)if(null!=/[\?&;]google_debug/.exec(document.URL)){var T=N,U=document.getElementsByTagName("head")[0];U||(U=document.createElement("head"),document.getElementsByTagName("html")[0].insertBefore(U,document.getElementsByTagName("body")[0]));var V=document.createElement("script");V.src=J(window)+"//"+K(T)+"/pagead/conversion_debug_overlay.js";U.appendChild(V)}else{try{var W;var X=N;"landing"==X.google_conversion_type||!X.google_conversion_id||X.google_remarketing_only&&X.google_disable_viewthrough?W=
!1:(X.google_conversion_date=new Date,X.google_conversion_time=X.google_conversion_date.getTime(),X.google_conversion_snippets="number"==typeof X.google_conversion_snippets&&0<X.google_conversion_snippets?X.google_conversion_snippets+1:1,"number"!=typeof X.google_conversion_first_time&&(X.google_conversion_first_time=X.google_conversion_time),X.google_conversion_js_version="7",0!=X.google_conversion_format&&1!=X.google_conversion_format&&2!=X.google_conversion_format&&3!=X.google_conversion_format&&
(X.google_conversion_format=1),v=new u(1),W=!0);if(W&&(document.write(Q()),N.google_remarketing_for_search&&!N.google_conversion_domain)){var O=N;S()}}catch(Y){}for(var Z=N,$=0;$<z.length;$++)Z[z[$]]=null};})();
