(function(a){a.fn.fitVids=function(b){var c={customSelector:null};b&&a.extend(c,b);return this.each(function(){var b="iframe[src*='player.vimeo.com'] iframe[src*='youtube.com'] iframe[src*='youtube-nocookie.com'] iframe[src*='kickstarter.com'][src*='video.html'] object embed".split(" ");c.customSelector&&b.push(c.customSelector);b=a(this).find(b.join(","));b=b.not("object object");b.each(function(){var b=a(this);if(!("embed"===this.tagName.toLowerCase()&&b.parent("object").length||b.parent(".fluid-width-video-wrapper").length)){var c=
"object"===this.tagName.toLowerCase()||b.attr("height")&&!isNaN(parseInt(b.attr("height"),10))?parseInt(b.attr("height"),10):b.height(),d=!isNaN(parseInt(b.attr("width"),10))?parseInt(b.attr("width"),10):b.width(),c=c/d;b.attr("id")||(d="fitvid"+Math.floor(999999*Math.random()),b.attr("id",d));b.wrap('<div class="fluid-width-video-wrapper"></div>').parent(".fluid-width-video-wrapper").css("padding-top",100*c+"%");b.removeAttr("height").removeAttr("width")}})})}})(jQuery);
(function(a){a.fn.unveil=function(b){function c(){h=e.filter(function(){var b=a(this),c=d.scrollTop(),e=c+d.height(),g=b.offset().top;return g+b.height()>=c-f&&g<=e+f});g=h.trigger("unveil");e=e.not(g)}var d=a(window),f=b||0,e=this,g,h,k;this.one("unveil",function(){k=this.getAttribute("data-src");this.setAttribute("src",k);this.removeAttribute("data-src")});d.scroll(c);d.resize(c);c();return this}})(jQuery);
(function(a){a.fn.infinite=function(b,c,d){return a.get(c,function(f){var e=a(a.parseHTML(f)).find(b).html();a(b).append(e);e=a(d);(newlink=a(a.parseHTML(f)).find(d).attr("href"))?a(e).attr("href",newlink):a(e).hide();window.location.href!=c&&history.pushState(null,null,c)})}})(jQuery);
jQuery(document).ready(function(a){a("body").removeClass("no-js");a(".noclickthrough").click(function(a){a.preventDefault()});a(".toggle").dropdown();a("#search-toggle").click(function(){a(".search-li").toggleClass("open")});a(window).scroll(function(){var b=!1;b=!0,timer=setTimeout(function(){scrollTop=a(this).scrollTop();150<scrollTop&&767<mte.width?a("#backtop").css("color","#333"):a("#backtop").css("color","#f9f9f9");if(!mte.single&&mte.scrollLoad&&scrollTop+a(window).height()>=0.75*a(document).height()){var c=
a("#loadmore").attr("href");c&&(a(".content-loop").infinite(".content-loop",c,"#loadmore"),mte.scrollLoad=!1,ga("send","pageview"))}480<mte.width&&(a(".content").height()>a(".sidebar").height()+660&&700<a(window).height())&&(sidebar_float=a("#floating-sidebar"),mte.floattop||(mte.floattop=sidebar_float.position().top),scrollTop+40>mte.floattop&&!sidebar_float.hasClass("fixed-top")?(sidebar_float.addClass("fixed-top"),sidebar_float.width(a(".sidebar").width())):scrollTop+40<mte.floattop&&sidebar_float.hasClass("fixed-top")&&
(sidebar_float.removeClass("fixed-top"),sidebar_float.width("100%")));b=!1},100)});a('a[data-toggle="modal"]').click(function(){modal_type=a(this).attr("data-type");if("login"==modal_type)var b=!0;else if("taf"==modal_type)var c=!0;a(this).attr("data-loaded")||(a("#modal").load(a(this).attr("href")+" #myModal",function(){b&&a('input[name="redirect_to"]').val(window.location.href);c&&(a('input[name="taf-subject"]').val("MakeTechEasier.com: "+a(".entry-title").text()),a('textarea[name="taf-message"]').text("Check this article out: "+
a(location).attr("href")))}),a('a[data-toggle="modal"]').removeAttr("data-loaded"),a(this).attr("data-loaded","1"));a("#modal").modal("toggle")});a(".backtop").click(function(){a("body,html").animate({scrollTop:0},800)});a(".listview").click(function(){a(this).toggleClass("active");a(".content-loop").toggleClass("list")});a(".entry-content").fitVids();a(".content img").each(function(){a(this).css("height","auto");a(this).css("width","auto")});a("#loadmore").on("click",function(b){a(".content-loop").infinite(".content-loop",
a(this).attr("href"),"#loadmore");ga("send","pageview")});a(document).on("click",".taf-send",function(){a.post(mte.ajaxurl,a("#taf-form").serialize(),function(b){a(".taf-status").html(b)})});mte.preview||(480>mte.width?serve_dfp_ads("mobile-adunit"):730>mte.width?serve_dfp_ads("medium-adunit"):979>mte.width?serve_dfp_ads("leaderboard-adunit"):serve_dfp_ads("adunit"),!mte.single&&730>mte.width&&(a(".content-loop").find(".bw-posts-adunit").addClass("ad_container"),serve_dfp_ads("bw-posts-adunit")));
979>mte.width?a(".entry-content img.lazy").unveil():a("img.lazy").unveil()});
function serve_dfp_ads(a){var b=jQuery("body").find("."+a);b.length&&googletag.cmd.push(function(){jQuery(b).each(function(){var b=jQuery(this).data(a).split(","),d=[];jQuery.each(b,function(a,b){var c=b.split("x");d.push([parseInt(c[0],10),parseInt(c[1],10)])});googletag.defineSlot("/1001566/"+jQuery(this).attr("id"),d,jQuery(this).attr("id")).addService(googletag.pubads())});googletag.enableServices();jQuery(b).each(function(){googletag.display(jQuery(this).attr("id"))})})};
